### ISSUE TITLE
AttributeError: 'str' object has no attribute 'columns'

### ISSUE THREAD

**Issue by antoniakrm** [IFCA/pycanon#1]
Hello :) Thank you for the new library, it is handy to have all the privacy-preserving techniques together. 
 
I would like to share a minor issue I encountered when trying to replicate the example you provided with the adult.csv dataset in the "Getting started" section. The anonymity function imported in the beginning seems to recognize the adult.csv as a string and not as a csv file.

Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
  File "/Users/user/.venv/lib/python3.8/site-packages/pycanon/anonymity/_k_anonymity.py", line 41, in k_anonymity
    aux_functions.check_qi(data, quasi_ident)
  File "/Users/user/.venv/lib/python3.8/site-packages/pycanon/anonymity/utils/aux_functions.py", line 65, in check_qi
    cols = data.columns
AttributeError: 'str' object has no attribute 'columns'

**Comment by judithspd** [comment]
Thank you very much for advising us about this issue. In previous versions of pyCANON you could enter both a pandas dataframe or a string with the file containing the data. However, in the current version (as shown in the documentation https://pycanon.readthedocs.io/en/latest/pycanon.anonymity.html) it is necessary to enter directly a pandas dataframe. This has been corrected in the getting started section and also in the examples. In case this is changed in upcoming versions and the path to the file can be entered directly, we will update it in the documentation. Thanks again for using pyCANON!
